#!/usr/bin/env python3
"""Generate the UNO Q device-tree overlay for a controller-less DSI panel.

For panels like the Waveshare 3.5inch DSI LCD (H)/(E): the panel takes 3V3 and
I2C from the FFC, initialises itself, and has no ATTINY-style power/backlight
controller, no reset line and no touch interrupt. The upstream generator
(dcuartielles/uno_q_dsi_displays tools/gen-overlay.py) drops the touch node
whenever there is no panel controller (`have_touch = touch_addr and have_ctrl`)
and always routes touch power/reset through that controller, so it cannot
describe this family. This script emits the same carrier wiring as the upstream
overlay that is verified on our 5" (cci_i2c0, mdss_dsi0, pm4125_l5) and adds a
polled Goodix node instead.

Usage: gen_overlay.py <panel.panel> <out.dts>
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

KEYS = [
    "PANEL_ID",
    "PANEL_COMPATIBLE",
    "PANEL_CTRL_ADDR",
    "DSI_LANES",
    "GOODIX_COMPATIBLE",
    "GOODIX_ADDR",
    "GOODIX_SIZE_X",
    "GOODIX_SIZE_Y",
]


def load_panel(path: str | Path) -> dict[str, str]:
    """Source the shell-syntax .panel file and read the variables back."""
    script = f". '{Path(path).resolve()}'; " + "; ".join(
        f'printf "%s=%s\\n" {k} "${k}"' for k in KEYS
    )
    out = subprocess.run(["sh", "-c", script], capture_output=True, text=True, check=True).stdout
    values: dict[str, str] = {}
    for line in out.splitlines():
        key, _, value = line.partition("=")
        values[key] = value
    return values


def render(d: dict[str, str]) -> str:
    if d.get("PANEL_CTRL_ADDR"):
        raise ValueError(
            "this panel has a controller; use the upstream generator (install.sh) instead"
        )
    for key in ("PANEL_ID", "PANEL_COMPATIBLE"):
        if not d.get(key):
            raise ValueError(f"panel definition is missing {key}")
    lanes = int(d.get("DSI_LANES") or 1)
    if not 1 <= lanes <= 4:
        raise ValueError(f"DSI_LANES must be 1..4, got {lanes}")
    lane_list = " ".join(str(i) for i in range(lanes))  # msm numbers lanes from 0

    touch = ""
    if d.get("GOODIX_ADDR"):
        addr = d["GOODIX_ADDR"].lower()
        if not addr.startswith("0x"):
            raise ValueError("GOODIX_ADDR must be hex, e.g. 0x14")
        size = ""
        if d.get("GOODIX_SIZE_X") and d.get("GOODIX_SIZE_Y"):
            size = (
                f"\t\t\t\ttouchscreen-size-x = <{d['GOODIX_SIZE_X']}>;\n"
                f"\t\t\t\ttouchscreen-size-y = <{d['GOODIX_SIZE_Y']}>;\n"
            )
        touch = (
            "\n\t\t\t/*\n"
            "\t\t\t * No interrupts property: the 15-pin FFC carries no touch INT\n"
            "\t\t\t * or RST line, and mainline goodix polls (17 ms) when it gets\n"
            "\t\t\t * no IRQ. No reset-gpios for the same reason.\n"
            "\t\t\t */\n"
            f"\t\t\ttouchscreen@{addr[2:]} {{\n"
            f'\t\t\t\tcompatible = "{d.get("GOODIX_COMPATIBLE") or "goodix,gt911"}";\n'
            f"\t\t\t\treg = <{addr}>;\n"
            f"{size}"
            "\t\t\t};\n"
        )

    return f"""// SPDX-License-Identifier: GPL-2.0
/*
 * {d["PANEL_ID"]} on Arduino UNO Q + UNO Media Carrier.
 *
 * GENERATED by tools/compact_display/gen_overlay.py from a .panel file.
 * Do not edit by hand.
 *
 * Controller-less panel: powered from the carrier DISPLAY connector's
 * PWR_3P3V (pin 22), self-initialising, no backlight control. The panel node
 * therefore has no power-supply or backlight phandles; panel-simple takes a
 * dummy regulator.
 */

/dts-v1/;
/plugin/;

/ {{
\t/* touch on the carrier's CCI I2C bus (DISPLAY pins 20/21 via TCA9406) */
\tfragment@0 {{
\t\ttarget = <&cci_i2c0>;
\t\t__overlay__ {{
\t\t\t#address-cells = <1>;
\t\t\t#size-cells = <0>;
{touch}\t\t}};
\t}};

\t/* the panel, attached directly to the DSI host */
\tfragment@2 {{
\t\ttarget = <&mdss_dsi0>;
\t\t__overlay__ {{
\t\t\t#address-cells = <1>;
\t\t\t#size-cells = <0>;
\t\t\tvdda-supply = <&pm4125_l5>;
\t\t\tstatus = "okay";

\t\t\tpanel: panel@0 {{
\t\t\t\tcompatible = "{d["PANEL_COMPATIBLE"]}";
\t\t\t\treg = <0>;

\t\t\t\tport {{
\t\t\t\t\tpanel_in: endpoint {{
\t\t\t\t\t\tremote-endpoint = <&mdss_dsi0_out>;
\t\t\t\t\t}};
\t\t\t\t}};
\t\t\t}};
\t\t}};
\t}};

\t/* DSI host output -> panel */
\tfragment@3 {{
\t\ttarget = <&mdss_dsi0_out>;
\t\t__overlay__ {{
\t\t\tremote-endpoint = <&panel_in>;
\t\t\tdata-lanes = <{lane_list}>;
\t\t}};
\t}};
}};
"""


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    try:
        text = render(load_panel(argv[1]))
    except ValueError as exc:
        print(f"gen_overlay: {exc}", file=sys.stderr)
        return 1
    Path(argv[2]).write_text(text)
    print(f"  wrote {argv[2]}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
